[package]
name = "rewrk"
version = "0.2.2"
authors = ["Harrison Burt <57491488+ChillFish8@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
clap = "2.33.3"
async-channel = "1.5.1"
colored = "2"
regex = "1.4.*"
